spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${artifactId}_dev
    username: ${artifactId}_dev_user
    password: ${artifactId}_dev_password
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    ${package}: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"