spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/${artifactId}}
    username: ${DATABASE_USERNAME:${artifactId}_user}
    password: ${DATABASE_PASSWORD:${artifactId}_password}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

server:
  port: ${PORT:8080}

logging:
  level:
    ${package}: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  file:
    name: /var/log/${artifactId}/${artifactId}.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never