spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${artifactId}
    username: ${artifactId}_user
    password: ${artifactId}_password
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false
  
  data:
    redis:
      host: localhost
      port: 6379
      password: ""

server:
  port: 8080

logging:
  level:
    ${package}: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never